// Tenantly API types. Mirrors the live /v1 API exactly.
export type ISODate = string;
export type PartialDate = string;
export type Lang = "en" | "es";
export type Category = "rent_increase_limits" | "just_cause_eviction" | "security_deposits" | "application_screening_fees" | "screening_restrictions" | "algorithmic_rent_setting";
export type Result = "applies" | "unknown" | "superseded" | "not_yet_effective" | "pending";
export type RuleStatus = "in_force" | "not_yet_effective" | "pending" | "failed";
export type Level = "state" | "county" | "city";
export type EvidenceTier = "A" | "B" | "C" | "C1";
export type Bilingual = { en: string; es: string };
export type StateCode = "CA" | "NJ" | "MA";
export interface Jurisdiction { id: string; level: Level; name: string; label: string; state: StateCode; geoid: string | null; in_scope: boolean; }
export interface JurisdictionStack { state: Jurisdiction; county: Jurisdiction | null; city: Jurisdiction | null; mailing_city: string | null; mailing_mismatch: boolean; note: Bilingual | null; resolution: { method: "point_in_polygon" | "state_only"; geocoder: "census_batch" | "census_oneline" | "nominatim" | "none"; census_agrees: boolean | null }; }
export interface FactValue { value: number | string | boolean | null; interval: [number | null, number | null] | null; source: "assessor" | "assessor_derived" | "user" | "derived" | "missing"; basis: string | null; record_conflict: boolean; label: Bilingual; }
export interface BuildingFacts { year_built: FactValue; units: FactValue; property_type: FactValue; subsidized: FactValue; use_code: string; use_description: string; source_dataset: string; zip_suspect: boolean; }
export interface AddressSummary { address_id: string; label: string; street: string; postal_city: string; zip: string | null; state: StateCode; lat: number; lon: number; legal_city: string | null; is_sample: boolean; }
export interface Citation { doc_id: string; cite: string; url: string; retrieved_at: string; quote: string; char_start: number | null; char_end: number | null; doc_sha256: string | null; tier: EvidenceTier; quote_source: "corpus" | "supplementary"; supplementary_doc: string | null; version_label: string | null; low_signal: boolean; }
export interface KeyValue { name: string; text: string; valid_from: ISODate | null; valid_to: ISODate | null; stale: boolean; stale_note: Bilingual | null; }
export interface ConditionTrace { label: Bilingual; fact: string; op: string; expected: string; actual: string | null; basis: string | null; result: "true" | "false" | "unknown"; }
export interface Conflict { with_rule_id: string | null; kind: "possible_preemption" | "barred_by_state" | "overlap"; explanation: Bilingual; evidence: Citation | null; active_from: ISODate | null; }
export interface OpenQuestion { oq_id: string; title: Bilingual; detail: Bilingual; rule_ids: string[]; sources: Citation[]; changes_answer_between: [ISODate, ISODate] | null; }
export interface ReasoningBoundary { checked: Bilingual[]; not_checked: Bilingual[]; assumptions: Bilingual[]; }
export interface RuleResult { rule_id: string; category: Category; title: string; jurisdiction: Jurisdiction; result: Result; rule_status: RuleStatus; effective_date: PartialDate | null; effective_note: Bilingual | null; summary: Bilingual; who: Bilingual; reason: Bilingual; key_values: KeyValue[]; conditions: ConditionTrace[]; caveats: Bilingual[]; missing_facts: string[]; superseded_by: string | null; governs_over: string[]; conflicts: Conflict[]; conflict_flag: boolean; citation: Citation; extra_citations: Citation[]; confidence: number; review_flag: boolean; open_question_ids: string[]; audio: { en: string | null; es: string | null }; }
export interface Finding { finding_id: string; category: Category; jurisdiction: Jurisdiction; reason_code: "barred_by_state" | "none_in_sources" | "motion_only" | "only_pending" | "failed_measure" | "text_not_supplied"; explanation: Bilingual; evidence: Citation[]; }
export interface CategoryBlock { category: Category; label: Bilingual; headline: Bilingual; results: RuleResult[]; findings: Finding[]; }
export interface DecisiveQuestion { fact: string; prompt: Bilingual; input: "year" | "integer" | "boolean" | "select"; options?: { value: string; label: Bilingual }[]; resolves_rule_ids: string[]; }
export interface UpcomingChange { date: ISODate; rule_id: string; title: string; from: Result | "none"; to: Result | "none"; summary: Bilingual; }
export interface LookupResponse { address: AddressSummary; jurisdiction: JurisdictionStack; facts: BuildingFacts; as_of: ISODate; categories: CategoryBlock[]; pending: RuleResult[]; failed: { rule_id: string; title: string; note: Bilingual; citation: Citation }[]; upcoming: UpcomingChange[]; counts: Record<Result, number>; decisive_question: DecisiveQuestion | null; open_questions: OpenQuestion[]; reasoning_boundary: ReasoningBoundary; facts_source: "data" | "user"; sources_retrieved_at: ISODate; is_projection: boolean; data_version: string; disclaimer: string; fallback: boolean; }
export interface TimelineSegment { start: ISODate; end: ISODate | null; lookup: LookupResponse; }
export interface TimelineResponse { address_id: string; range: { start: ISODate; end: ISODate }; breakpoints: { date: ISODate; label: Bilingual; rule_ids: string[] }[]; segments: TimelineSegment[]; data_version: string; }
export interface AddressIndexItem { address_id: string; label: string; postal_city: string; legal_city: string | null; state: StateCode; zip: string | null; lat: number; lon: number; }
export interface ResolveResponse { match_type: "sample" | "geocoded" | "not_found"; address: AddressSummary | null; jurisdiction: JurisdictionStack | null; candidates: AddressIndexItem[]; geocoder: "index" | "census" | "nominatim" | null; }
export interface RuleDetail { rule_id: string; category: Category; title: string; jurisdiction: Jurisdiction; rule_status: RuleStatus; effective_date: PartialDate | null; effective_note: Bilingual | null; requirement: string; summary: Bilingual; who: Bilingual; coverage_text: Bilingual; exemptions: { description: Bilingual; citation: Citation | null }[]; key_values: KeyValue[]; penalty: string | null; citation: Citation; extra_citations: Citation[]; relations: { type: string; other_rule_id: string | null; explanation: Bilingual; evidence: Citation; active_from: ISODate | null }[]; confidence: number; review_flag: boolean; open_question_ids: string[]; provenance: { models: string[]; prompt_versions: Record<string, string>; votes: Record<string, string>; adjudicated_fields: string[]; audit_ids: string[] }; counts_at_default_date: Record<Result, number>; }
export interface SourceDoc { doc_id: string; title: string; url: string; retrieved_at: string; doc_sha256: string | null; sha_ok: boolean | null; jurisdiction_label: string; doc_type: string; low_signal: boolean; versions: { label: string; valid_from: ISODate | null; valid_to: ISODate | null; in_force_on_default: boolean }[]; window: { text: string; start: number; end: number; highlights: { start: number; end: number; rule_id: string }[] }; total_chars: number; }
export interface AffectedAddress { address_id: string; label: string; lat: number; lon: number; legal_city: string | null; before: { rule_id: string; result: Result | "none" }[]; after: { rule_id: string; result: Result | "none" }[]; conflict_flag: boolean; }
export interface ChangeEvent { change_id: string; kind: "test" | "ingest" | "watch"; test_id: string | null; title: string; test_type: "as_of" | "boundary" | "pending" | "negative" | "with_without"; summary: Bilingual; created_at: string; rule_ids: string[]; compare: { before: ISODate; after: ISODate } | { on: ISODate } | { mode: "with_without"; on: ISODate }; affected_count: number; conflict_count: number; expected_check: { passed: boolean; detail: string } | null; affected: AffectedAddress[]; }
export type IngestStage = "received" | "sectionize" | "triage" | "extract" | "verify" | "crosscheck" | "calendar" | "link" | "explain" | "diff" | "impact" | "ready" | "published" | "failed";
export interface IngestJob { job_id: string; status: "running" | "ready" | "published" | "failed"; stage: IngestStage; started_at: string; finished_at: string | null; stages: { stage: IngestStage; status: "pending" | "running" | "done" | "failed"; detail: string; ms: number | null }[]; result: null | { rules: RuleDetail[]; findings: Finding[]; relations: RuleDetail["relations"]; impact: { affected_count: number; sample: AffectedAddress[]; effective_date: PartialDate | null; conflicts: number }; verification: { quotes_checked: number; quotes_verified: number; rejected: number }; cost_usd: number; cache_hit: boolean; }; error: { code: string; message: string } | null; }
export interface ProofResponse { data_version: string; compiled_at: string; selfscore: { components: { name: string; score: number; max: number; note: string }[]; key: "silver"; raw_report: string } | null; change_checks: { test_id: string; passed: boolean; affected: number; expected: number; conflicts: number; expected_conflicts: number }[]; verification: { rules: number; tier_counts: Record<EvidenceTier, number>; quotes_verified: number; rejected_candidates: number; adjudicated_fields: number; mean_confidence: number }; facts: { derived_units: number; record_conflicts: number; zip_suspect: number; missing_year_built: number }; geo: { matched_batch: number; matched_oneline: number; matched_nominatim: number; unmatched: number; mailing_mismatches: number; census_disagreements: number }; plain_language: { mean_grade_en: number; max_grade_en: number; es_coverage: number }; latency: { measured_at: string; lookup_p50_ms: number; lookup_p95_ms: number; custom_p50_ms: number; llm_baseline_ms: number | null } | null; cost: { total_usd: number; by_stage: Record<string, number> }; open_questions: OpenQuestion[]; limitations: Bilingual[]; }
export interface Meta { app: "Tenantly"; api_version: "v1"; data_version: string; compiled_at: string; default_as_of: ISODate; sources_retrieved_at: ISODate; as_of_range: { start: ISODate; end: ISODate }; categories: { key: Category; label: Bilingual }[]; jurisdictions: Jurisdiction[]; counts: { rules: number; findings: number; addresses: number; docs_text: number; docs_link_only: number }; persistence: "memory" | "postgres"; demo_mode: "live" | "replay"; disclaimer: string; }
