"""Render recon results to DATASET_NOTES.md, keeping hand-written Decisions/Cuts sections."""

from __future__ import annotations

import json

from engine import config, recon

START = "<!-- recon:start -->"
END = "<!-- recon:end -->"

DEFAULT_TAIL = """
## Deviations from CORPUS_ATLAS.md (verified against the files)
1. **Manifest sha256 does not match the text files.** None of the 54 `text/D###.txt` files
   hashes to its manifest `sha256`, under any of: raw bytes, body after the header, stripped,
   CRLF/LF variants.
   The manifest hash most likely fingerprints the original capture (PDF/HTML), not the plain-text
   conversion. Decision: the loader records `sha_ok=false` / `hash_mismatch` in the audit and
   continues; citations carry the sha256 of the text file we actually read (`doc_sha256`), which is
   what byte-offset verification needs. The manifest sha256 is kept as `manifest_sha256`.
2. **Link-only count.** 32 manifest rows are `link-only`; D056 has status `manual: 403 ...` (capture
   `yes`, no text file). Together they are the 33 rows of `links_only.csv`. D056 is treated as a
   known gap (MA criminal-record screening, 803 CMR 5).

## Decisions
Recorded when PLAN.md is silent (PLAN.md section 21).

## Cuts
Optional items cut to keep a phase on time.
"""


def render(checks: list[dict]) -> str:
    lines = [
        START,
        "## Recon results",
        "",
        "Generated by `make recon`. Checks with a fixed expectation are marked OK or DIFFERS;",
        "observations without an expectation are listed for reference.",
        "",
        "| Claim | Expected | Actual | Status |",
        "|---|---|---|---|",
    ]
    for c in checks:
        status = "observed" if c["expected"] is None else ("OK" if c["ok"] else "**DIFFERS**")
        exp = "-" if c["expected"] is None else f"`{json.dumps(c['expected'], sort_keys=True)}`"
        act = json.dumps(c["actual"], sort_keys=True, ensure_ascii=False)
        if len(act) > 400:
            act = act[:397] + "..."
        lines.append(f"| {c['claim']} | {exp} | `{act}` | {status} |")
    lines.append(END)
    return "\n".join(lines)


def write_dataset_notes() -> int:
    checks = recon.run()
    path = config.ROOT / "DATASET_NOTES.md"
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    tail = DEFAULT_TAIL
    if END in old:
        tail = old.split(END, 1)[1]
    body = "# DATASET_NOTES\n\nDeviations between the files and CORPUS_ATLAS.md / PLAN.md.\n\n"
    path.write_text(body + render(checks) + tail, encoding="utf-8")
    return sum(1 for c in checks if c["expected"] is not None and not c["ok"])
