/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AAddressIdRouteImport } from './routes/a.$addressId'
import { Route as ChangesIndexRouteImport } from './routes/changes.index'
import { Route as ChangesIdRouteImport } from './routes/changes.$id'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesRuleIdRouteImport } from './routes/rules.$ruleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AAddressIdRoute = AAddressIdRouteImport.update({
  id: '/a/$addressId',
  path: '/a/$addressId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesIndexRoute = ChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesIdRoute = ChangesIdRouteImport.update({
  id: '/changes/$id',
  path: '/changes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingest': typeof IngestRoute
  '/proof': typeof ProofRoute
  '/watch': typeof WatchRoute
  '/a/$addressId': typeof AAddressIdRoute
  '/changes/$id': typeof ChangesIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingest': typeof IngestRoute
  '/proof': typeof ProofRoute
  '/watch': typeof WatchRoute
  '/a/$addressId': typeof AAddressIdRoute
  '/changes/$id': typeof ChangesIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/changes': typeof ChangesIndexRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingest': typeof IngestRoute
  '/proof': typeof ProofRoute
  '/watch': typeof WatchRoute
  '/a/$addressId': typeof AAddressIdRoute
  '/changes/$id': typeof ChangesIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ingest'
    | '/proof'
    | '/watch'
    | '/a/$addressId'
    | '/changes/$id'
    | '/rules/$ruleId'
    | '/changes/'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ingest'
    | '/proof'
    | '/watch'
    | '/a/$addressId'
    | '/changes/$id'
    | '/rules/$ruleId'
    | '/changes'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ingest'
    | '/proof'
    | '/watch'
    | '/a/$addressId'
    | '/changes/$id'
    | '/rules/$ruleId'
    | '/changes/'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IngestRoute: typeof IngestRoute
  ProofRoute: typeof ProofRoute
  WatchRoute: typeof WatchRoute
  AAddressIdRoute: typeof AAddressIdRoute
  ChangesIdRoute: typeof ChangesIdRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  ChangesIndexRoute: typeof ChangesIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$addressId': {
      id: '/a/$addressId'
      path: '/a/$addressId'
      fullPath: '/a/$addressId'
      preLoaderRoute: typeof AAddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/': {
      id: '/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof ChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/$id': {
      id: '/changes/$id'
      path: '/changes/$id'
      fullPath: '/changes/$id'
      preLoaderRoute: typeof ChangesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IngestRoute: IngestRoute,
  ProofRoute: ProofRoute,
  WatchRoute: WatchRoute,
  AAddressIdRoute: AAddressIdRoute,
  ChangesIdRoute: ChangesIdRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  ChangesIndexRoute: ChangesIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
